# Generated by Django 5.2.12 on 2026-03-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="bonus",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="payroll",
            name="pf",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="payroll",
            name="tax",
            field=models.FloatField(default=0),
        ),
    ]
