# Generated by Django 5.2.11 on 2026-03-17 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="applied_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Sick Leave", "Sick Leave"),
                    ("Casual Leave", "Casual Leave"),
                    ("Emergency Leave", "Emergency Leave"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leave",
            name="reason",
            field=models.TextField(default="no reason provided"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
