# Generated by Django 5.2.11 on 2026-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_leave_applied_on_leave_leave_type_leave_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Sick", "Sick Leave"),
                    ("Casual", "Casual Leave"),
                    ("Earned", "Earned Leave"),
                ],
                max_length=20,
            ),
        ),
    ]
