# Generated by Django 5.2.11 on 2026-03-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="leave_documents/"),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("CL", "Casual Leave (CL)"),
                    ("SL", "Sick Leave (SL)"),
                    ("EL", "Earned Leave (EL)"),
                    ("LOP", "Loss of Pay (LOP)"),
                    ("OH", "Optional Holiday"),
                ],
                max_length=10,
            ),
        ),
    ]
