# Generated by Django 5.2.11 on 2026-03-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("attendance", "0005_alter_leave_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("basic_salary", models.FloatField()),
                ("hra", models.FloatField(default=0)),
                ("allowances", models.FloatField(default=0)),
                ("leave_deduction", models.FloatField(default=0)),
                ("other_deductions", models.FloatField(default=0)),
                ("gross_salary", models.FloatField()),
                ("net_salary", models.FloatField()),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.registration",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "month", "year")},
            },
        ),
    ]
