# Generated by Django 5.0.6 on 2026-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_delete_payroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="manager_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
